version: 2
jobs:
  beam:
    working_directory: ~/fialyzer
    docker:
      - image: erlang:21.1.2-alpine
    steps:
      - checkout
      - run:
          name: Install System Deps
          command: apk add --no-cache ca-certificates make bash
      - run:
          name: Compile erl files
          command: make beam
      - persist_to_workspace:
          root: .
          paths:
            # CircleCI does not support globstar pattern (`**/*.beam`).
            # So you must list concrete filepaths if you want to add BEAM files.
            - ./test/blackbox-test/test-cases/*.beam
  build:
    working_directory: ~/fialyzer
    docker:
      - image: ocaml/opam2:alpine-3.8-ocaml-4.07
    steps:
      - run:
          name: Install System Deps
          # NOTE: You must install git and openssh before checkout, otherwise submodule will not be updated.
          command: sudo apk add --no-cache m4 make zlib-dev gmp-dev perl git openssh bash
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install
          command: eval $(opam config env) && opam repo add remote-default https://opam.ocaml.org && opam pin add -y fialyzer .
      - run:
          name: Test
          # NOTE: Don't run `make test` because `make test` requires Erlang/OTP.
          command: eval $(opam config env) && make unit-test && make blackbox-test
      - run:
          name: OCamldoc
          command: eval $(opam config env) && opam install odoc && make doc
      - persist_to_workspace:
          root: _build/default
          paths: _doc/_html
  satysfi:
    working_directory: ~/fialyzer
    docker:
      - image: amutake/satysfi:0.0.3-dev2019.02.13
    steps:
      - checkout
      - run:
          name: Build PDF
          command: eval $(opam env) && satysfi docs/derivation-rules.saty
      - persist_to_workspace:
          root: .
          paths: docs/*.pdf
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Install gh-pages and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@example.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "ea:f5:81:bc:ff:e7:ac:e5:80:00:95:93:31:24:87:57"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --message "[skip ci] doc upload" --dist workspace/_doc/_html --dest odoc
            gh-pages --message "[skip ci] doc upload" --dist workspace/docs --dest docs
workflows:
  version: 2
  all:
    jobs:
      - beam
      - build:
          requires:
            - beam
      - satysfi
      - docs-deploy:
          requires:
            - build
            - satysfi
          filters:
            branches:
              only: satysfi
