version: 2
jobs:
  build:
    working_directory: ~/fialyzer # use /fialyzer for local circleci cli
    docker:
      - image: ocaml/opam:alpine-3.5_ocaml-4.03.0
    steps:
      - checkout
      - run:
          name: Install System Deps
          command: sudo apk add --update m4 make
      - run:
          name: Install
          command: eval $(opam config env) && opam repo add remote-default https://opam.ocaml.org && cd obeam && opam pin add -y obeam . && cd ../ && opam pin add -y fialyzer .
